// Chart packs (Phase 3): per-country statutory charts generated by
// coa_convert live in packs/ (INSERT scripts with an __ENTITY__
// placeholder). LoadPack executes one pack for an entity, mirrors its rows
// 1:1 into ferp_accounts (the posting chart), and ensures the VEN/ACH
// journals auto-posting needs. Every step is idempotent (ON CONFLICT DO
// NOTHING), so a crash between steps repairs on reload.
package finance

import (
	"context"
	"embed"
	"fmt"
	"strings"

	"github.com/YASSERRMD/forge-erp/backend/internal/platform"
)

//go:embed packs/pack_*.sql
var packFS embed.FS

// ChartPacks enumerates loadable statutory charts (pack code → source).
var ChartPacks = map[string]string{
	"FR": "packs/pack_fr.sql", // PCG25-DEV (metropolitan standard)
	"DE": "packs/pack_de.sql", // SKR03
	"US": "packs/pack_us.sql", // US-BASE
}

// ChartPackLoader executes a statutory pack for one entity. *PGStore is the
// only implementation: pack loading executes SQL scripts, so it is
// inherently PostgreSQL-backed (handlers answer 501 otherwise).
type ChartPackLoader interface {
	LoadChartPack(ctx context.Context, db platform.DBTX, entityID int64, pack string) (LoadReport, error)
}

// LoadReport counts what one load (re)applied.
type LoadReport struct {
	Pack     string `json:"pack"`
	Accounts int64  `json:"accounts"` // ferp_accounts rows ensured
}

// LoadChartPack validates the pack code, executes its INSERT script for the
// entity, mirrors pack rows into the posting chart, and ensures VEN/ACH.
func (s *PGStore) LoadChartPack(ctx context.Context, db platform.DBTX, entityID int64, pack string) (LoadReport, error) {
	pack = strings.ToUpper(strings.TrimSpace(pack))
	file, ok := ChartPacks[pack]
	if !ok {
		return LoadReport{}, fmt.Errorf("finance: unknown chart pack %q: %w", pack, platform.ErrValidation)
	}
	if entityID <= 0 {
		return LoadReport{}, fmt.Errorf("finance: entity required: %w", platform.ErrUnauthorized)
	}
	raw, err := packFS.ReadFile(file)
	if err != nil {
		return LoadReport{}, err
	}
	script := strings.ReplaceAll(string(raw), "__ENTITY__", fmt.Sprintf("%d", entityID))
	if _, err := db.Exec(ctx, script); err != nil {
		return LoadReport{}, fmt.Errorf("finance: load pack %s: %w", pack, err)
	}
	tag, err := db.Exec(ctx, `INSERT INTO ferp_accounts (entity_id, code, label, type)
		SELECT entity_id, code, label, category FROM ferp_accounting_accounts
		WHERE entity_id=$1 AND pack=$2
		ON CONFLICT (entity_id, code) DO NOTHING`, entityID, pack)
	if err != nil {
		return LoadReport{}, fmt.Errorf("finance: mirror pack %s: %w", pack, err)
	}
	if _, err := db.Exec(ctx, `INSERT INTO ferp_journals (entity_id, code, label)
		VALUES ($1,'VEN','Sales'),($1,'ACH','Purchases')
		ON CONFLICT (entity_id, code) DO NOTHING`, entityID); err != nil {
		return LoadReport{}, fmt.Errorf("finance: ensure journals: %w", err)
	}
	return LoadReport{Pack: pack, Accounts: tag.RowsAffected()}, nil
}
